version: "2"
services:
    db:
        image: mysql:5.7
        ports:
        - "3307:3306"
        container_name: db
        environment:
        - MYSQL_ROOT_PASSWORD=pass
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - MYSQL_DATABASE=twitter
        volumes: 
        - ./db:/docker-entrypoint-initdb.d/:ro

    app:
        image: brocaneli/twitter-hashtags:latest
        container_name: app
        depends_on:
        - db
        - elasticsearch
        links: 
        - db
        - logstash
        ports: 
        - "5001:5000"
        environment:
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass
        - TOKEN=AAAAAAAAAAAAAAAAAAAAANauPgEAAAAAaI9AKNPQRqk9cQpGexh1cbB1huo%3D9QZHoxPi581aZMpqEKzeJ9VWWgjehtf51IPg05IcKPL2tx0x0f
    
    prometheus:
        image: prom/prometheus
        container_name: prometheus
        depends_on: 
        - app
        links:
        - app
        volumes:
            - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090

    grafana:
        image: grafana/grafana
        container_name: grafana
        volumes:
            - ./monitoring/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
            - ./monitoring/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
            - ./monitoring/dashboard.json:/var/lib/grafana/dashboards/dasboard.json
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=pass@123
        - GF_USERS_ALLOW_SIGN_UP=false
        ports:
            - 3000:3000
        links: 
            - prometheus
        depends_on:
            - prometheus

    logstash:
        image: logstash:7.12.1
        container_name: logstash
        ports: 
        - 5044:5044
        links: 
        - elasticsearch
        command: logstash -f /etc/logstash/conf.d/logstash.conf --debug
        volumes:
        - ./logging:/etc/logstash/conf.d

    elasticsearch:
        image: elasticsearch:7.12.1
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=elasticsearch
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
        ports:
        - 9200:9200

    kibana:
        image: kibana:7.12.1
        container_name: kibana
        ports:
        - 5601:5601
        environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
        links:
        - elasticsearch
        depends_on: 
        - elasticsearch
        - logstash
